# Generated by Django 4.2 on 2023-04-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ecode', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('salary', models.FloatField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.dept')),
            ],
        ),
    ]
